---
# Main list of tasks to be executed.
#
#   Fail the play if it runs on an unsupported system or architecture.
- name: Assert platform is supported
  tags: packerio
  assert:
    that:
      - ansible_os_family in packerio_supported_platforms
      - ansible_architecture in packerio_supported_architectures


#   Packer download link alters based on system and architecture
- name: Load version vars
  tags: packerio
  with_first_found:
    - ../vars/versions/{{ packerio_version }}_{{ ansible_system }}.yml
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"

- name: Assert version vars
  tags: packerio
  assert:
    that:
      packerio_sha256sum not in (None, "")


#   Ensure unarchive modules' dependencies
- name: Include OS specific vars
  tags: packerio
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install unarchive module dependencies
  tags: packerio
  with_items: packerio_package_list
  action: "{{ ansible_pkg_mgr }} state=present name={{ item }}"


#   Download packer to the local source directory
- name: Install packer.io download directory (local)
  tags: packerio
  local_action: file
    state=directory
    owner=0
    group=0
    mode=2777
    dest={{ local_ansible_data_path }}

- name: Download packer.io distribution (local)
  tags: packerio
  sudo: no
  local_action: get_url
    url={{ packerio_mirror }}/{{ packerio_filename }}
    dest={{ local_ansible_data_path }}/{{ packerio_filename }}
    mode=0644
    sha256sum={{ packerio_sha256sum }}


#   Install packer
- name: Ensure installation directory
  tags: packerio
  file:
    state=directory
    owner=0
    group=0
    mode=0755
    dest={{ packerio_install_dir }}/{{ packerio_version }}

- name: Install packer
  tags: packerio
  unarchive:
    src={{ local_ansible_data_path }}/{{ packerio_filename }}
    dest={{ packerio_install_dir }}/{{ packerio_version }}

- name: Gathering installed binaries
  tags: packerio
  register: packerio_installed_binaries
  shell: ls -1 {{ packerio_install_dir }}/{{ packerio_version }}/packer*

- name: Linking binaries into system PATH
  tags: packerio
  when: packerio_bin_path != packerio_install_dir
  with_items: packerio_installed_binaries.stdout_lines
  file:
    state=link
    force=true
    src={{ item }}
    dest={{ packerio_bin_path }}/{{ item|basename }}
